/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.login;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.maan.common.base.CommonBaseForm;

/**
 * MyEclipse Struts Creation date: 10-24-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class LoginForm extends CommonBaseForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String method;

	/** password property */
	private String password;

	/** enteredPassword property */
	private String enteredPassword;

	/** enteredLoginId property */
	private String enteredLoginID;

	private String userId;

	private String userType;

	private String loginId;

	private String skin;

	private int skinId;

	private List menuList;
	
	/** status property */
	
	private String status;
	
	private String startDate;
	
	private String endDate;
	
	private String insCompanyId;
	
	private String stateCode;
	
	private String districtCode;
	
	private String stateName;
	
	private String districtName;
	
	private String investigationOfficerCode;
	
	/*
	 * Generated Methods
	 */

	public String getDistrictName() {
		return districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public String getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	public String getStateCode() {
		return stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getInsCompanyId() {
		return insCompanyId;
	}

	public void setInsCompanyId(String insCompanyId) {
		this.insCompanyId = insCompanyId;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(final String status) {
		this.status = status;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(final ActionMapping mapping,
			final HttpServletRequest request) {
		enteredPassword = "";
	}

	public ActionErrors validate(final ActionMapping mapping,
			final HttpServletRequest request) {
		return null;
	}

	/**
	 * Returns the password.
	 * 
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            The password to set
	 */
	public void setPassword(final String password) {
		this.password = password;
	}

	/**
	 * Returns the enteredPassword.
	 * 
	 * @return String
	 */
	public String getEnteredPassword() {
		return enteredPassword;
	}

	/**
	 * Set the enteredPassword.
	 * 
	 * @param enteredPassword
	 *            The enteredPassword to set
	 */
	public void setEnteredPassword(final String enteredPassword) {
		this.enteredPassword = enteredPassword;
	}

	/**
	 * Returns the enteredLoginId.
	 * 
	 * @return String
	 */
	public String getEnteredLoginID() {
		return enteredLoginID;
	}

	/**
	 * Set the enteredLoginId.
	 * 
	 * @param enteredLoginId
	 *            The enteredLoginId to set
	 */
	public void setEnteredLoginID(final String enteredLoginId) {
		this.enteredLoginID = enteredLoginId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(final String userId) {
		this.userId = userId;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(final String method) {
		this.method = method;
	}

	public List getMenuList() {
		return menuList;
	}

	public void setMenuList(final List menuList) {
		this.menuList = menuList;
	}

	public String getSkin() {
		return skin;
	}

	public void setSkin(final String skin) {
		this.skin = skin;
	}

	public int getskinId() {
		return skinId;
	}

	public void setskinId(final int skinId) {
		this.skinId = skinId;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(final String userType) {
		this.userType = userType;
	}

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getInvestigationOfficerCode() {
		return investigationOfficerCode;
	}

	public void setInvestigationOfficerCode(String investigationOfficerCode) {
		this.investigationOfficerCode = investigationOfficerCode;
	}
}