/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.admin.bankRejection;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2010
 * 
 * XDoclet definition:
 * @struts.form name="bankForm"
 */
public class BankRejectionForm extends ActionForm {
	

	private String rejectionid;
	private String rejectiontypedesc;
	private String rejectiontypeid;
	private String status;
	private int bankID;
	private String page;

	public String getPage() {
		return page;
	}

	public void setPage(String page) {
		this.page = page;
	}


	public int getBankID() {
		return bankID;
	}


	public void setBankID(int bankID) {
		this.bankID = bankID;
	}


	public String getRejectionid() {
		return rejectionid;
	}


	public void setRejectionid(String rejectionid) {
		this.rejectionid = rejectionid;
	}


	public String getRejectiontypedesc() {
		return rejectiontypedesc;
	}


	public void setRejectiontypedesc(String rejectiontypedesc) {
		this.rejectiontypedesc = rejectiontypedesc.toUpperCase();
	}


	public String getRejectiontypeid() {
		return rejectiontypeid;
	}


	public void setRejectiontypeid(String rejectiontypeid) {
		this.rejectiontypeid = rejectiontypeid.toUpperCase();
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
}