/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.menu;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 09-08-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="menuForm"
 */
public class MenuForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** method property */
	private String method;
	private String userName;
	private String district;
	private String districtId;	
	private String stateId;
    private String stateName;	
	private String districtName;
	
	/*
	 * Generated Methods
	 */

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getDistrictId() {
		return districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	public String getDistrictName() {
		return districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public String getStateId() {
		return stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(final ActionMapping mapping,
			final HttpServletRequest request) {
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(final ActionMapping mapping,final HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the method.
	 * 
	 * @return String
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * Set the method.
	 * 
	 * @param method
	 *            The method to set
	 */
	public void setMethod(final String method) {
		this.method = method;
	}	
}