/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.admin.usermanipulation;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.maan.common.base.CommonBaseForm;

/**
 * MyEclipse Struts Creation date: 09-11-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginCreationForm"
 */
public class UserManipulationForm extends CommonBaseForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** password property */
	private int id;
    
	private String password;

	/** userName property */
	private String userName;

	/** loginID property */
	private String loginID;

	/** userType property */
	private String userType;

	/** createdBy property */
	private String createdBy;

	/** status property */
	private String status;
	
	/** insurance company name property   */
	private String insuranceCompany;
	private Map insuranceCompName;

	/** rePassword property */
	private String rePassword;

	/** method property */
	private String method;

	private String mode;

	private String searchOn;

	private String searchFor;

	private String oldPassword;

	private String fromList;

	private String[] menuIDs;
	
	private Map userTypeList;
	
	private Map loginIDList;
	
	private String loginSts;
	
	private String main;
	
	private String insCompanyId;
	
	private String[] stateCode;
	
	private String[] districtCode;

	/*
	 * Generated Methods
	 */

	public String getMain() {
		return main;
	}

	public void setMain(String main) {
		this.main = main;
	}

	public String getLoginSts() {
		return loginSts;
	}

	public void setLoginSts(String loginSts) {
		this.loginSts = loginSts;
	}

	public Map getUserTypeList() {
		return userTypeList;
	}

	public void setUserTypeList(Map userTypeList) {
		this.userTypeList = userTypeList;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		password = "";
		rePassword = "";
	}

	/**
	 * Returns the password.
	 * 
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Returns the userName.
	 * 
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * Set the userName.
	 * 
	 * @param userName
	 *            The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Returns the loginID.
	 * 
	 * @return String
	 */
	public String getLoginID() {
		return loginID;
	}

	/**
	 * Set the loginID.
	 * 
	 * @param loginID
	 *            The loginID to set
	 */
	public void setLoginID(String loginID) {
		this.loginID = loginID;
	}

	/**
	 * Returns the userType.
	 * 
	 * @return String
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * Set the userType.
	 * 
	 * @param userType
	 *            The userType to set
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * Returns the createdBy.
	 * 
	 * @return String
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * Set the createdBy.
	 * 
	 * @param createdBy
	 *            The createdBy to set
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Returns the status.
	 * 
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Returns the rePassword.
	 * 
	 * @return String
	 */
	public String getRePassword() {
		return rePassword;
	}

	/**
	 * Set the rePassword.
	 * 
	 * @param rePassword
	 *            The rePassword to set
	 */
	public void setRePassword(String rePassword) {
		this.rePassword = rePassword;
	}

	/**
	 * Returns the method.
	 * 
	 * @return String
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * Set the method.
	 * 
	 * @param method
	 *            The method to set
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSearchFor() {
		return searchFor;
	}

	public void setSearchFor(String searchFor) {
		this.searchFor = searchFor;
	}

	public String getSearchOn() {
		return searchOn;
	}

	public void setSearchOn(String searchOn) {
		this.searchOn = searchOn;
	}

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String[] getMenuIDs() {
		return menuIDs;
	}

	public void setMenuIDs(String[] menuIDs) {
		this.menuIDs = menuIDs;
	}

	public String getFromList() {
		return fromList;
	}

	public void setFromList(String fromList) {
		this.fromList = fromList;
	}

	public Map getLoginIDList() {
		return loginIDList;
	}

	public void setLoginIDList(Map loginIDList) {
		this.loginIDList = loginIDList;
	}

	public String getInsuranceCompany() {
		return insuranceCompany;
	}

	public void setInsuranceCompany(String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	public Map getInsuranceCompName() {
		return insuranceCompName;
	}

	public void setInsuranceCompName(Map insuranceCompName) {
		this.insuranceCompName = insuranceCompName;
	}

	public String[] getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String[] districtCode) {
		this.districtCode = districtCode;
	}

	public String[] getStateCode() {
		return stateCode;
	}

	public void setStateCode(String[] stateCode) {
		this.stateCode = stateCode;
	}

	public String getInsCompanyId() {
		return insCompanyId;
	}

	public void setInsCompanyId(String insCompanyId) {
		this.insCompanyId = insCompanyId;
	}

	

	
}