/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.admin.bank;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2010
 * 
 * XDoclet definition:
 * @struts.form name="bankForm"
 */
public class BankForm extends ActionForm {
	
	private String bankid;
	private String bankname;
	private String banktable;
	private String chequeno;
	private String chequeamt;
	private String chequestatus;
	private String reason;
	private String active;
	private String page;
	private String receiptNo;
	private int bankID;
	
	
	public String getPage() {
		return page;
	}


	public void setPage(String page) {
		this.page = page;
	}


	public String getActive() {
		return active;
	}


	public void setActive(String active) {
		this.active = active;
	}


	public String getBankid() {
		return bankid;
	}


	public void setBankid(String bankid) {
		this.bankid = bankid.toUpperCase();
	}


	public int getBankID() {
		return bankID;
	}


	public void setBankID(int bankID) {
		this.bankID = bankID;
	}


	public String getBankname() {
		return bankname;
	}


	public void setBankname(String bankname) {
		this.bankname = bankname;
	}


	public String getBanktable() {
		return banktable;
	}


	public void setBanktable(String banktable) {
		this.banktable = banktable;
	}


	public String getChequeamt() {
		return chequeamt;
	}


	public void setChequeamt(String chequeamt) {
		this.chequeamt = chequeamt;
	}


	public String getChequeno() {
		return chequeno;
	}


	public void setChequeno(String chequeno) {
		this.chequeno = chequeno;
	}


	public String getChequestatus() {
		return chequestatus;
	}


	public void setChequestatus(String chequestatus) {
		this.chequestatus = chequestatus;
	}


	public String getReason() {
		return reason;
	}


	public void setReason(String reason) {
		this.reason = reason;
	}


	public String getReceiptNo() {
		return receiptNo;
	}


	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}


	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
}