/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.common.use;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class CommonDispatchForm extends ActionForm {

	private int detailsMasterId;
	private String transactionId;
	private String invoiceNo;
	private String memberId;
	private String transactionType;
	private String transactionDesc;
	private String hospitalName;
	private String hospitalAuthId;
	private String hospitalStateName;
	private String hospitalDistrictName;
	private String packageCode;
	private String packageDesc;
	private String dateOfAdmission;
	private String dateOfDischarge;
	private String mortality;
	private String disease;
	private String noOfDays;
	private String preAuthCode;
	private String transDate;
	private String transTime;
	private String gender;
	private String stateName;
	private String districtName;
	private String insComanyCode;
	private String patientName;
	private String urnNo;
	private String stateCode;
	private String districtCode;
	private String blockCode;
	private String blockName;
	private String panchayatCode;
	private String panchayatName;
	private String villageCode;
	private String villageName;
	private String totclaimAmount;
	private String totBlockAmount;
	private String insufficientFund;
	private String insufficientAmount;
	private String amountClaimed;
	private String travelAmountClaimed;
	private String currentTotalAmount;
	private String claimNo;
	private String paymentBlockNo;
	private String amountPaid;
	private String paymentStatus;
	private String claimBlockNo;
	private String investigationBlockNo;
	private String investOfficerCode;
	private String investOfficer;
	private String investStartDate;
	private String investEndDate;
	private String investRemarks;
	private String investStatus;
	private String remarks;
	private String tdsamount;
	private String chequeamount;
	
	public String getChequeamount() {
		return chequeamount;
	}


	public void setChequeamount(String chequeamount) {
		this.chequeamount = chequeamount;
	}


	public String getTdsamount() {
		return tdsamount;
	}


	public void setTdsamount(String tdsamount) {
		this.tdsamount = tdsamount;
	}


	public String getRemarks() {
		return remarks;
	}


	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}


	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		return null;
	}

	
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		
	}


	public String getAmountClaimed() {
		return amountClaimed;
	}


	public void setAmountClaimed(String amountClaimed) {
		this.amountClaimed = amountClaimed;
	}


	public String getAmountPaid() {
		return amountPaid;
	}


	public void setAmountPaid(String amountPaid) {
		this.amountPaid = amountPaid;
	}


	public String getBlockCode() {
		return blockCode;
	}


	public void setBlockCode(String blockCode) {
		this.blockCode = blockCode;
	}


	public String getBlockName() {
		return blockName;
	}


	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}


	public String getClaimBlockNo() {
		return claimBlockNo;
	}


	public void setClaimBlockNo(String claimBlockNo) {
		this.claimBlockNo = claimBlockNo;
	}


	public String getClaimNo() {
		return claimNo;
	}


	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}


	public String getCurrentTotalAmount() {
		return currentTotalAmount;
	}


	public void setCurrentTotalAmount(String currentTotalAmount) {
		this.currentTotalAmount = currentTotalAmount;
	}


	public String getDateOfAdmission() {
		return dateOfAdmission;
	}


	public void setDateOfAdmission(String dateOfAdmission) {
		this.dateOfAdmission = dateOfAdmission;
	}


	public String getDateOfDischarge() {
		return dateOfDischarge;
	}


	public void setDateOfDischarge(String dateOfDischarge) {
		this.dateOfDischarge = dateOfDischarge;
	}


	public String getDisease() {
		return disease;
	}


	public void setDisease(String disease) {
		this.disease = disease;
	}


	public String getDistrictCode() {
		return districtCode;
	}


	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}


	public String getDistrictName() {
		return districtName;
	}


	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}


	public String getGender() {
		return gender;
	}


	public void setGender(String gender) {
		this.gender = gender;
	}


	public String getHospitalAuthId() {
		return hospitalAuthId;
	}


	public void setHospitalAuthId(String hospitalAuthId) {
		this.hospitalAuthId = hospitalAuthId;
	}


	public String getHospitalDistrictName() {
		return hospitalDistrictName;
	}


	public void setHospitalDistrictName(String hospitalDistrictName) {
		this.hospitalDistrictName = hospitalDistrictName;
	}


	public String getHospitalName() {
		return hospitalName;
	}


	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}


	public String getHospitalStateName() {
		return hospitalStateName;
	}


	public void setHospitalStateName(String hospitalStateName) {
		this.hospitalStateName = hospitalStateName;
	}


	public String getInsComanyCode() {
		return insComanyCode;
	}


	public void setInsComanyCode(String insComanyCode) {
		this.insComanyCode = insComanyCode;
	}


	public String getInsufficientAmount() {
		return insufficientAmount;
	}


	public void setInsufficientAmount(String insufficientAmount) {
		this.insufficientAmount = insufficientAmount;
	}


	public String getInsufficientFund() {
		return insufficientFund;
	}


	public void setInsufficientFund(String insufficientFund) {
		this.insufficientFund = insufficientFund;
	}


	public String getInvestEndDate() {
		return investEndDate;
	}


	public void setInvestEndDate(String investEndDate) {
		this.investEndDate = investEndDate;
	}


	public String getInvestigationBlockNo() {
		return investigationBlockNo;
	}


	public void setInvestigationBlockNo(String investigationBlockNo) {
		this.investigationBlockNo = investigationBlockNo;
	}


	public String getInvestOfficerCode() {
		return investOfficerCode;
	}


	public void setInvestOfficerCode(String investOfficerCode) {
		this.investOfficerCode = investOfficerCode;
	}


	public String getInvestRemarks() {
		return investRemarks;
	}


	public void setInvestRemarks(String investRemarks) {
		this.investRemarks = investRemarks;
	}


	public String getInvestStartDate() {
		return investStartDate;
	}


	public void setInvestStartDate(String investStartDate) {
		this.investStartDate = investStartDate;
	}


	public String getInvestStatus() {
		return investStatus;
	}


	public void setInvestStatus(String investStatus) {
		this.investStatus = investStatus;
	}


	public String getInvoiceNo() {
		return invoiceNo;
	}


	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}


	public String getMemberId() {
		return memberId;
	}


	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}


	public String getMortality() {
		return mortality;
	}


	public void setMortality(String mortality) {
		this.mortality = mortality;
	}


	public String getNoOfDays() {
		return noOfDays;
	}


	public void setNoOfDays(String noOfDays) {
		this.noOfDays = noOfDays;
	}


	public String getPackageCode() {
		return packageCode;
	}


	public void setPackageCode(String packageCode) {
		this.packageCode = packageCode;
	}


	public String getPackageDesc() {
		return packageDesc;
	}


	public void setPackageDesc(String packageDesc) {
		this.packageDesc = packageDesc;
	}


	public String getPanchayatCode() {
		return panchayatCode;
	}


	public void setPanchayatCode(String panchayatCode) {
		this.panchayatCode = panchayatCode;
	}


	public String getPanchayatName() {
		return panchayatName;
	}


	public void setPanchayatName(String panchayatName) {
		this.panchayatName = panchayatName;
	}


	public String getPatientName() {
		return patientName;
	}


	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}


	public String getPaymentBlockNo() {
		return paymentBlockNo;
	}


	public void setPaymentBlockNo(String paymentBlockNo) {
		this.paymentBlockNo = paymentBlockNo;
	}


	public String getPaymentStatus() {
		return paymentStatus;
	}


	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}


	public String getPreAuthCode() {
		return preAuthCode;
	}


	public void setPreAuthCode(String preAuthCode) {
		this.preAuthCode = preAuthCode;
	}


	public String getStateCode() {
		return stateCode;
	}


	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}


	public String getStateName() {
		return stateName;
	}


	public void setStateName(String stateName) {
		this.stateName = stateName;
	}


	public String getTotBlockAmount() {
		return totBlockAmount;
	}


	public void setTotBlockAmount(String totBlockAmount) {
		this.totBlockAmount = totBlockAmount;
	}


	public String getTotclaimAmount() {
		return totclaimAmount;
	}


	public void setTotclaimAmount(String totclaimAmount) {
		this.totclaimAmount = totclaimAmount;
	}


	public String getTransactionDesc() {
		return transactionDesc;
	}


	public void setTransactionDesc(String transactionDesc) {
		this.transactionDesc = transactionDesc;
	}


	public String getTransactionId() {
		return transactionId;
	}


	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}


	public String getTransactionType() {
		return transactionType;
	}


	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}


	public String getTransDate() {
		return transDate;
	}


	public void setTransDate(String transDate) {
		this.transDate = transDate;
	}


	public String getTransTime() {
		return transTime;
	}


	public void setTransTime(String transTime) {
		this.transTime = transTime;
	}


	public String getTravelAmountClaimed() {
		return travelAmountClaimed;
	}


	public void setTravelAmountClaimed(String travelAmountClaimed) {
		this.travelAmountClaimed = travelAmountClaimed;
	}


	public String getUrnNo() {
		return urnNo;
	}


	public void setUrnNo(String urnNo) {
		this.urnNo = urnNo;
	}


	public String getVillageCode() {
		return villageCode;
	}


	public void setVillageCode(String villageCode) {
		this.villageCode = villageCode;
	}


	public String getVillageName() {
		return villageName;
	}


	public void setVillageName(String villageName) {
		this.villageName = villageName;
	}


	public int getDetailsMasterId() {
		return detailsMasterId;
	}


	public void setDetailsMasterId(int detailsMasterId) {
		this.detailsMasterId = detailsMasterId;
	}


	public String getInvestOfficer() {
		return investOfficer;
	}


	public void setInvestOfficer(String investOfficer) {
		this.investOfficer = investOfficer;
	}
}