/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.maan.common.use;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.maan.common.LogManager;

/** 
 * MyEclipse Struts
 * Creation date: 12-13-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CommonDispatchAction extends DispatchAction {
	
	private String forward="";
	//private final CommonCB cCB = new CommonCB();
	
	public ActionForward memberInformation(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
			forward="memberDetails";
			final CommonDispatchForm cForm = (CommonDispatchForm)form;
			final int detailsMasterId=request.getParameter("detailsMasterId")==null?0:Integer.parseInt(request.getParameter("detailsMasterId"));
			LogManager.push("Inside CommonDispatchAction - memberInformation -> detailsMasterId: "+detailsMasterId);
			cForm.setDetailsMasterId(detailsMasterId);
			try{
			//cCB.getFullDetailsByMasterId(cForm);
			}catch(Exception e){LogManager.push("Exception In memberInformation: "+e);}
			LogManager.push("Exit CommonDispatchAction - memberInformation");
		return mapping.findForward(forward);
	}
}